import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stulture</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:h-screen h-[60vh] bg-[url('../public/top-layer.png')] bg-no-repeat bg-cover  w-screen bg-center">
        <div className="flex justify-between md:p-10 p-5">
          <h2>STULTURE</h2>
          <button className="bg-orange-500 rounded-lg px-5 md:py-2 py-1">
            CHALLENGES
          </button>
        </div>

        <div className="flex justify-around md:mt-[30vh] mt-20 max-md:text-xs">
          <div className="text-center">
            <p>PLANET</p>
            <p className="font-bold">STULTURE</p>
          </div>
          <div className=""></div>
          <div className="text-center">
            <p>HABITANTS</p>
            <p className="font-bold">DESIGNERS</p>
          </div>
        </div>
      </div>

        <div className="max-md:h-[80vh] h-[250vh] bg-[url('../public/merged.png')] bg-no-repeat bg-cover w-screen ">
          <div className="w-2/5 m-10 flex flex-col p-5 md:p-10 justify-between bg-black bg-opacity-70 h-4/6 md:h-1/2 rounded-lg">
            <div className="text-[8px] md:text-lg">
              <h2 className="font-bold my-2">THE FUTURE</h2>
              <p>Be a part of the next generation of superior designers</p>
            </div>
            <div className="text-[8px] md:text-lg">
              <h2 className="font-bold my-2">COMPETITIONS</h2>
              <p>Be a part of the next generation of superior designers</p>
            </div>
            <div className="text-[8px] md:text-lg">
              <h2 className="font-bold my-2">DES vs DES</h2>
              <p>Compete with designers all over the Stulture Network</p>
            </div>
          </div>
        </div>

      <div className="bg-[url('../public/leagues.png')] h-screen  bg-no-repeat bg-cover w-screen bg-center">

        <h2 className="font-bold text-center text-2xl pt-10">LEAGUES</h2>
      </div>

      <div className="bg-[url('../public/bg.png')] min-h-[50vh] p-10 -mt-20 bg-no-repeat bg-cover w-screen bg-center">

        <div className="flex justify-around max-w-4xl m-auto md:pt-20 pt-5">

          <img className="max-md:w-2/12" src="/carbon.png" alt="" />
          <img className="max-md:w-2/12" src="/styrene.png" alt="" />
          <img className="max-md:w-2/12" src="/pixel.png" alt="" />
          <img className="max-md:w-2/12" src="/arial.png" alt="" />

        </div>

        <div className="bg-black bg-opacity-30 w-4/5 text-center max-md:text-[8px] rounded-lg m-auto mt-10 md:p-10 p-5">
          <p>Accumulate PTS by outworking yourself and move up the Leagues</p>
        </div>

        <div className="text-center pt-10">
          <h2 className="font-bold ">STLTRVRS</h2>
          <h2>COMMING SOON</h2>
          <p className="max-md:text-[10px] mt-5">Making concept visualisation more immersive and entertaining</p>
        </div>

      </div>


    </>
  );
}
